import Header from './header.js';
import Slider from './slider.js';
import Content from './content.js';
import GetImg from './img.js';
import GetIconFont from './Iconfont.js';
import './style/index.scss';
new Header();
new Slider();
new Content();
new GetImg();
new GetIconFont();
